### PR TITLE
Convert from the `chrono` crate to the `time` crate

### LINKED ISSUE #24: Transition from `chrono` crate
`time-rs/time` exposed a security vulnerability when using `localtime_r` on Unix-like systems, which could lead to a segmentation fault (GHSA-wcg3-cvx6-7396). `time` has since patched the issue, but the `chrono` crate is also affected by the vulnerability, both due to it's dependency on `time` 0.1, and due to its own internal use of `localtime_r`. At the time of writing this ticket, the chrono crate is still locked in discussion for the best way to resolve this security vulnerability (see chronotope/chrono#578).

In the interim, we should transition to using `time` 0.3 directly, which exposes a similar enough interface to `chrono` that the transition should be simple to do, while also avoiding the CVE.

### PR DESCRIPTION
**Pull request by pxslip**
A few places here where I'm not sure about rust best practices/semantics. I'll add comments in the appropriate places. This PR fixes #24

### CODE REVIEW

File: src/chatbot/commands.rs [hunk 1]
```diff
@@ -59,8 +60,11 @@ impl Command {
                     }
                 }
                 ScriptAction::Wait(duration) => {
-                    tokio::time::sleep(duration.to_std().unwrap()) // Safe to unwrap because we check for positive values at the time the command is created
-                        .await;
+                    tokio::time::sleep(StdDuration::new(
+                        duration.whole_seconds().unsigned_abs(),
+                        duration.subsec_nanoseconds().unsigned_abs(),
+                    )) // Safe to unwrap because we check for positive values at the time the command is created
+                    .await;
```
Comment (pxslip) [inline src/chatbot/commands.rs:67]: Supposedly `time::Duration` has a function `abs_std` that converts a, potentially negative, Duration to `std::time::Duration`. Attempting to use it introduced a compiler error indicating the method was private. The alternative is just to build a new `std::time::Duration` as here.

File: src/lib.rs [hunk 2]
```diff
@@ -43,19 +44,21 @@ pub enum StateCommand {
...
+fn serialize_datetime<S>(date_time: &OffsetDateTime, s: S) -> Result<S::Ok, S::Error>
 where
     S: Serializer,
 {
-    const TIME_FMT: &str = "%H:%M:%S";
-    s.serialize_str(&date_time.format(TIME_FMT).to_string())
+    // const TIME_FMT: &str = "%H:%M:%S"; // temporarily leaving for reference
+    const FORMAT: &[FormatItem] = format_description!("[hour]:[minute]:[second]");
+    let formatted = date_time.format(FORMAT);
+    s.serialize_str(&formatted.unwrap()) //unwrapping here, good practice or bad?
```
Comment (pxslip) [inline src/lib.rs:54]: I'm not sure semantically/best practice for `let` vs `const` here. An alternative implementation could look like:

```rust
    let format = format_description!("[hour]:[minute]:[second]");
    let formatted = date_time.format(&format);
```

Not sure if there is a preference, and if so why.

**Comment by pxslip** [comment]
Should also note that I used `unwrap` a few times. If my brain is following the logic properly I've used them safely. If that is not the case let me know.

File: src/chatbot/commands.rs (hunk 1 above)
Comment (trollham) [reply src/chatbot/commands.rs:67]: We don't allow for the creation of commands with a negative duration for the Wait action, see the implementation of the action_parser (if you can stomach it; that code is a mess). That makes it safe to unwrap here.

There's a conversion function provided as part of the `core::convert::TryFrom` trait, and `time::Duration` specializes an implementation for `std::time::Duration`. See the examples provided [here](https://github.com/time-rs/time/blob/8b78d3f0ee12e8466cacc035c1d3bd953484c84f/tests/integration/duration.rs#L381).

File: src/lib.rs (hunk 2 above)
Comment (trollham) [reply src/lib.rs:54]: `const` is a compile-time constant. Similar to `static`, except rather than refer to a place in memory, it substitutes the value in for the name directly. Think of it as similar to C's preprocessor macros, but constrained to values, not expressions (besides `const fn` expressions IIRC, but that's another can of worms). 

Can we switch this to use RFC 339 instead of the hacked H:M:S I put here originally? `time` provides a formatter for it, and it'd be better to use something standardized. If the front-end needs less info in that column we can handle it there, but for now I think it's fine to just send the entire RFC 339-formatted string.

File: Cargo.toml [hunk 3]
```diff
@@ -22,6 +22,7 @@ reqwest = "0.11"
 serde = { version = "1.0", features = ["rc"] }
 serde_json = "1.0"
 thiserror = "1.0"
+time = { version = "0.3.5", features = ["serde", "formatting", "macros", "local-offset"] }
```
Comment (trollham) [inline Cargo.toml:25]: I think we can leave off `macros` as a dependency, since we don't need to perform compile-time timestamp validation

Comment (trollham) [reply Cargo.toml:25]: Please remove `chrono` as a dependency.

**Review by trollham — CHANGES_REQUESTED** [review]

File: Cargo.toml (hunk 3 above)
Comment (pxslip) [reply Cargo.toml]: Done and done.

**Comment by pxslip** [comment]
Rust type conversions are odd beasts. Though the explicit error handling is impressive.

These commits implement RFC3339 for serialization, improves the `time::Duration` -> `std::time::Duration` type conversion, and removes `chrono` and the `macro` feature.

**Review by trollham — APPROVED** [review]
